name: Swift

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift/swift:6.0
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run Tests
        run: swift test
