name: Swift

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: compnerd/gha-setup-swift@v0.4.0
        with:
          swift-version: swift-6.3.3-release
          swift-build: 6.3.3-RELEASE

      - name: Build
        run: swift build

      - name: Run Tests
        run: swift test
